### ISSUE TITLE
Add this usage example?

### ISSUE THREAD

**Issue by sdwolf** [goertzenator/erlang_nif-sys#12]
Hello,

I've created this repo with an example of using `erlang_nif-sys` with a simple erlang project: https://github.com/sdwolf/rustfromerl

It features:
- a Dockerfile for setting up the environment with the latest stable versions of erlang and rust.
- a rebar3 project
- automatic compilation of rust nifs with the help of this rebar3 plugin: https://github.com/sdwolf/rebar3_rust
- a matrix multiplication module with functions written in both languages to show performance difference.

Would you be interested in adding this to the examples? If yes I can create a PR.

Cheers!

**Comment by goertzenator** [comment]
Absolutely!  I have some comments but I'll put them on your repo.
